catalog/urls.py
# coding=utf-8
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^materiais/$', views.product_list, name='product_list'),
    url(r'^(?P<slug>[\w_-]+)/$', views.category, name='category'),
    url(r'^material/(?P<slug>[\w_-]+)/$', views.product, name='product'),
]

checkout/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^pedido/adicionar/(?P<slug>[\w_-]+)/$', views.add_cart, name='add_cart'),
   	url(r'^relacao/$', views.cart_item, name='cart_item'),
   	url(r'^finalizar/$', views.checkout, name='checkout'),
   	url(r'^meus-pedidos/$', views.order_list, name='order_list'),
   	url(r'^meus-pedidos/(?P<pk>\d+)/$', views.order_detail, name='order_detail'),
   	url(r'^imprimir/(?P<pk>\d+)/$', views.printpdf, name='printpdf'),
]

sisalmox/urls.py
# coding=utf-8

from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout

from core import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^contato/$', views.contact, name='contact'),
    url(r'^legislacao/$', views.laws, name='laws'),
    url(r'^entrar/$', login,{'template_name': 'login.html'}, name='login'),
    url(r'^sair/$', logout,{'next_page': 'index'}, name='logout'),
    url(r'^conta/', include('accounts.urls', namespace='accounts')),
    url(r'^pedidos/', include('checkout.urls', namespace='checkout')),
    url(r'^requisicao/', include('catalog.urls', namespace='catalog')),
    url(r'^pesquisar/', include('searchengine.urls', namespace='searchengine')),
]

checkout/models.py
from django.db import models
from django.conf import settings
from catalog.models import Product, Unidades
from django.contrib import messages

class CartItemManager(models.Manager):
	def add_item(self,cart_key,product):
		if self.filter(cart_key=cart_key, product=product).exists():
			created = False
			cart_item = self.get(cart_key=cart_key, product=product)
			cart_item.quantity = cart_item.quantity + 1
			cart_item.save()
		else:
			created = True
			cart_item = CartItem.objects.create(
			    cart_key=cart_key, product=product, price=product.price, unid=product.unid, codigo=product.codigo, description=product.description,
			)
		return cart_item, created

class CartItem(models.Model):
	cart_key = models.CharField('Chave do Carrinho',max_length=40,db_index=True)
	product = models.ForeignKey('catalog.Product',verbose_name='Produto')
	quantity = models.PositiveIntegerField('Quantidade',default=1)
	price = models.DecimalField('Preço',decimal_places=2,max_digits=8)
	unid = models.ForeignKey('catalog.Unidades', verbose_name='Unidades')
	sub = models.DecimalField('Sub',decimal_places=2,max_digits=8)
	codigo = models.CharField('Código Comprasnet', max_length=6)
	description = models.TextField('Descrição')

	objects = CartItemManager()

	class Meta:
		verbose_name = 'Item do Carrinho'
		verbose_name_plural = 'Itens do Carrinho'
		unique_together = (('cart_key','product'),)

	def sub(self):
		sub = 0
		return sub

	def __str__(self):
		return '{} [{}]'.format(self.product,self.quantity, self.sub)


class OrderManager(models.Manager):
	def create_order(self,user,cart_itens):
		order = self.create(user = user)
		for cart_item in cart_itens:
			order_item = OrderItem.objects.create(order = order,product=cart_item.product,quantity=cart_item.quantity,price=cart_item.price,unid=cart_item.unid,codigo=cart_item.codigo,description=cart_item.description)
		return order

	def create_list(self,user,cart_itens):
		lista = self.create(user = user)
		for cart_item in cart_itens:
			list_item = OrderItem.objects.create(order = order,product=cart_item.product,quantity=cart_item.quantity,price=cart_item.price,unid=cart_item.unid,codigo=cart_item.codigo,description=cart_item.description)
		return lista

class Order(models.Model):

	STATUS_CHOICES = (
		(0,'Aguardando Publicação'),
		(1,'Concluida'),
		(2,'Cancelada'),
	)

	user = models.ForeignKey(settings.AUTH_USER_MODEL,verbose_name = "Usuário")
	status = models.IntegerField('Situação',choices=STATUS_CHOICES,default=0,blank=True)
	created = models.DateTimeField('Criado em',auto_now_add=True)
	modified = models.DateTimeField('Atualizado em',auto_now=True)

	objects = OrderManager()

	class Meta:
		verbose_name = 'Pedido'
		verbose_name_plural = 'Pedidos'

	def __str__(self):
		return 'Pedido #{}'.format(self.pk)

	def products(self):
		products_ids = self.itens.values_list('product')
		return Product.objects.filter(pk__in=products_ids)

	def total(self):
		aggregate_queryset = self.itens.aggregate(
			total=models.Sum(
				models.F('price') * models.F('quantity'), output_field=models.DecimalField()
			)
		)
		return aggregate_queryset['total']

class OrderItem(models.Model):
	order = models.ForeignKey(Order,verbose_name='Pedido',related_name='itens')
	product = models.ForeignKey('catalog.Product',verbose_name='Produto')
	quantity = models.PositiveIntegerField('Quantidade',default=1)
	price = models.DecimalField('Preço',decimal_places=2,max_digits=8)
	unid = models.ForeignKey('catalog.Unidades', verbose_name='Unidades')
	sub = models.DecimalField('Sub',decimal_places=2,max_digits=8,default='0.0')
	codigo = models.CharField('Código Comprasnet', max_length=6)
	description = models.TextField('Descrição', blank=True)

	class Meta:
		verbose_name = 'Item do Pedido'
		verbose_name_plural = 'Itens do Pedido'

	def sub(self):
		return self.price * self.quantity

	def __str__(self):
		return 'Pedido:{}, Produto:{}'.format(self.order,self.product,self.sub)

def post_save_cart_item(instance,**kwargs):
	if instance.quantity < 1:
		instance.delete()

models.signals.post_save.connect(post_save_cart_item,sender=CartItem,dispatch_uid='post_save_cart_item')

checkout/views.py
# coding=utf-8

from django.shortcuts import get_object_or_404,redirect, render
from django.views.generic import RedirectView, TemplateView, ListView, DetailView, View
from django.forms import modelformset_factory
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from catalog.models import Product, Unidades
from .models import CartItem,Order
from django.http import HttpResponse

class CreateCartItemView(LoginRequiredMixin,RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        product = get_object_or_404(Product, slug=self.kwargs['slug'])
        if self.request.session.session_key is None:
            self.request.session.save()
        cart_item, created = CartItem.objects.add_item(
            self.request.session.session_key, product
        )
        if created:
            messages.success(self.request, 'Produto adicionado com sucesso')
        else:
            messages.success(self.request, 'Produto atualizado com sucesso')
        return reverse('checkout:cart_item')

add_cart = CreateCartItemView.as_view()

class CartItemView(LoginRequiredMixin,TemplateView):
    template_name = 'checkout/cart.html'
    def get_formset(self, clear=False):
        CartItemFormSet = modelformset_factory(
            CartItem, fields=('quantity',), can_delete=True, extra=0
        )

        session_key = self.request.session.session_key
        if session_key:
            if clear:
                formset = CartItemFormSet(
                    queryset=CartItem.objects.filter(cart_key=session_key)
                )
            else:
                formset = CartItemFormSet(
                    queryset=CartItem.objects.filter(cart_key=session_key),
                    data=self.request.POST or None
                )
        else:
            formset = CartItemFormSet(queryset=CartItem.objects.none())
        return formset

    def get_context_data(self, **kwargs):
        context = super(CartItemView, self).get_context_data(**kwargs)
        context['formset'] = self.get_formset()
        return context

    def post(self, request, *args, **kwargs):
        formset = self.get_formset()
        context = self.get_context_data(**kwargs)
        if formset.is_valid():
            formset.save()
            messages.success(request, 'Pedido atualizado com sucesso')
            context['formset'] = self.get_formset(clear=True)
        return self.render_to_response(context)

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)

cart_item = CartItemView.as_view()

class CheckoutView(LoginRequiredMixin,TemplateView):
    template_name = 'checkout/checkout.html'
    def get(self,request,*args,**kwargs):
        session_key = request.session.session_key
        if session_key and CartItem.objects.filter(cart_key = session_key).exists():
            cart_itens = CartItem.objects.filter(cart_key = session_key)
            order = Order.objects.create_order(user=request.user,cart_itens = cart_itens)
            cart_itens.delete()
        else:
            messages.warning(request,'Não há itens no pedido')
            return redirect('checkout:cart_item')
        return super(CheckoutView,self).get(request,*args,**kwargs)

checkout = CheckoutView.as_view()

class OrderListView(LoginRequiredMixin, ListView):
    template_name = 'checkout/order_list.html'
    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)

order_list = OrderListView.as_view()

class OrderDetailView(LoginRequiredMixin, DetailView):
    template_name = 'checkout/order_detail.html'
    paginate_by = 2
    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)

order_detail = OrderDetailView.as_view()

class PrintPdf(LoginRequiredMixin, DetailView):
    template_name = 'checkout/printpdf.html'
    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)

printpdf = PrintPdf.as_view()

checkout/templates/checkout/cart.html
{% extends "catalog/index.html" %}

{% load widget_tweaks %}

{% block title %}
Requisição de Material
{% endblock %}

{% block catalog_container %}
<div class="page-header">
    <h1 class="text-center">Requisição de Material</h1>
</div>
  <div class="row">
    <div class="col-md-9 col-md-offset-1">

      {% if formset|length <= 10 %}
      {% else %}
      <div class="alert alert-danger">
        <strong>ATENÇÃO!</strong> Seu pedido não poderá conter mais de 10 materiais diferentes.
      </div>
      {% endif %}

      <h5 style="color:red; "><b>*ATENÇÃO: Antes de finalizar o seu pedido, clique em ATUALIZAR QUANTIDADES</b></h5>
      <form class="" action="" method="post">
        {% csrf_token %}
        {{ formset.management_form }}
        <table class="table table-bordered">
          <thead>
            <th width="50">
                Item
            </th>
            <th>
                Código
            </th>
            <th>
                Descrição
            </th>
            <th>
                Unidade
            </th>
            <th class="text-center" style="width: 10%;">
                Quantidade
            </th>
            <th>
              Ação
            </th>
          </thead>
          <tbody>

            {% for form in formset %}
              <tr>
                <td>
                  {{ forloop.counter }}
                </td>
                <td>
                    {{ form.instance.codigo }}
                </td>
                <td>
                    {{ form.instance.product }}
                </td>
                <td>
                      {{ form.instance.unid }}
                </td>
                <td>
                    {% render_field form.quantity class="form-control" %}
                </td>
                <td class="text-center">
                    <button value="on" type="submit" name="{{ form.DELETE.html_name }}" class="btn btn-danger btn-sm">Remover</button>
                    {{ form.id }}
                </td>
              </tr>
          </tbody>
          {% endfor %}
        </table>

        {% if formset|length <= 10 %}
        <p class="text-right">
          <a href="{% url 'catalog:product_list' %}" class="pull-left btn btn-info">Continuar Pedido</a>
          <button type="submit" class="btn btn-success" name="button">Atualizar Quantidades</button>
          <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Finalizar Pedido</button>
        </p>
        {% else %}
        <p class="text-right">
          <a href="{% url 'catalog:product_list' %}" class="pull-left btn btn-info">Continuar Pedido</a>
          <button type="submit" class="btn btn-success" name="button">Atualizar Quantidades</button>
          <button type="button" class="btn btn-primary disabled" data-toggle="modal" data-target="#myModal">Finalizar Pedido</button>
        </p>
        {% endif %}

        <!-- Modal -->
        <div class="modal fade" id="myModal" role="dialog">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h4 class="modal-title">ATENÇÃO!!!</h4>
              </div>
              <div class="modal-body">
                <p>Certifique-se de ter clicado em ATUALIZAR QUANTIDADES.</P>
                <p>Após finalizado, o pedido não poderá ser alterado.</p>
              </div>
              <div class="modal-footer">
                <a href="{% url 'checkout:cart_item' %}" class="pull-left btn btn-success">Voltar</a>
                <a href="{% url 'checkout:checkout' %}" class="btn btn-primary">Aceitar e Finalizar Pedido</a>
              </div>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

checkout/templates/checkout/checkout.html
{% extends "base.html" %}

{% block title %}
Finalização do Pedido
{% endblock %}

{% block container %}

<div class="page-header">
    <h1>Finalização da Compra</h1>
</div>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="alert alert-success">
            Seu pedido de compras foi realizado com sucesso.
        </div>
        <p>
            Você deve imprimir o pedido, assinar e abrir processo encaminhando à Direção do CES.
        </p>

        <p class="text-right">
          <a href="{% url 'checkout:order_list' %}" class="btn btn-primary">Imprimir</a>
        </p>
    </div>
</div>
{% endblock %}

checkout/templates/checkout/order_detail.html
{% extends "accounts/index.html" %}

{% load pagination %}

{% load widget_tweaks %}

{% block title %}Pedido{% endblock %}

{% block accounts_container %}

<h2>Pedido N° {{ order.pk }} Data: {{ object.created|date:"d/m/Y H:i" }}<a href="{% url 'checkout:printpdf' order.pk %}" class="pull-right btn btn-primary">Imprimir</a></h2>
<table class="table table-bordered">
  <h3>Itens do Pedido</h3>
  <thead>
    <tr>
      <th>Item</th>
      <th>Código</th>
      <th>Descrição do Material</th>
      <th>Unidade</th>
      <th>Quant</th>
    </tr>
  </thead>
  <tbody>
    {% for item in object.itens.all %}
    <tr>
      <td>{{ forloop.counter }}</td>
      <td>{{ item.codigo }}</td>
      <td>{{ item.description }}</td>
      <td>{{ item.unid }}</td>
      <td>{{ item.quantity }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}

checkout/templates/checkout/order_list.html
{% extends "accounts/index.html" %}

{% load pagination %}

{% load widget_tweaks %}

{% block title %}Meus Pedidos{% endblock %}

{% block accounts_container %}
    <h2>Meus Pedidos</h2>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th><center>N°</center></th>
          <th><center>Produtos</center></th>
          <th><center>Data</center></th>
          <th colspan="2"><center>Ações</center></th>
        </tr>
      </thead>
      <tbody>
        {% for order in object_list %}
        <tr>
          <td>
            <center>{{ order.pk }}</center></a>
          </td>
          <td>
            {% for product in order.products %}
              {{ product.codigo }} - {{ product.name }}{% if not forloop.last %}<br />{% endif %}
            {% endfor %}
          </td>
          <td>
            {{ order.created|date:"d/m/Y h:m" }}
          </td>
          <td class="text-center">
            <a href="{% url 'checkout:order_detail' order.pk %}"class="btn btn-success" role="button"><center>Detalhes</center></a>
          </td>
          <td class="text-center">
            <a href="{% url 'checkout:printpdf' order.pk %}" class="btn btn-primary" role="button"><center>Imprimir</center></a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  {% pagination request paginator page_object %}
  {% endblock %}

checkout/templates/checkout/printpdf.html
<!DOCTYPE html>
<html>
  <head>
    <title>Página de Impressão</title>
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </head>

    <script type="text/javascript">
      function printpage()
        { window.print() }
    </script>
  </head>

  <table>
    <tr>
      <td>
        <img  align="left" width="400" height="100"
        src="http://www.cdsa.ufcg.edu.br/home/arq/logomarca/logo_atual/UFCG-lateral.png" alt="" />
      </td>
      <td width="50"></td>
      <td width="300">
        <table class="table table-bordered">
          <tr>
            <td align="center" width="100">RM</td>
            <td colspan="3"></td>
          </tr>
          <tr>
            <td align="center" width="100">NF</td>
            <td colspan="3"></td>
          </tr>
          <tr>
            <td width="130">Data de Emissão</td>
            <td width="50"></td>
            <td width="50"></td>
            <td width="50"></td>
          </tr>
        </table>
      </td>
    </tr>
  </table>

  <center>
      <h4>REQUISIÇÃO DE MATERIAL</h4>
  </center>

  <body>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th width="20">Código</th>
          <th>Descrição do Material</th>
          <th width="130">Unidade</th>
          <th width="20">Quant</br>Solicitada</th>
          <th width="20">Quant</br>Autorizada</th>
        </tr>
      </thead>
      <tbody>
        {% for item in object.itens.all %}
        <tr>
          <td>{{ item.codigo }}</td>
          <td>{{ item.description }}</td>
          <td>{{ item.unid }}</td>
          <td>{{ item.quantity }}</td>
          <td></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <p>
    <div align="right">
      Cuite, {% now "d/F/Y" %}
    </div>
    <p>
    <p>
    <p>
    <div align="center">
      __________________________________________<br/>
      <b>{{ user.name }}</b><br/>
      {{ user.cargo }}</br>
      Mat.: {{ user.matricula }}
    </div>
  </font>
  </body>
</html>