accounts/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^alterar-dados/$', views.update_user, name='update_user'),
    url(r'^alterar-senha/$',views.password_change,name='password_change'),
    url(r'^usuarios/$',views.userlist,name='userlist'),
    url(r'^registro/$', views.register, name='register')
]



from django.conf.urls import url,include
from accounts import views

urlpatterns = [
    url(r'^registro/$',views.register,name='register'),
    url(r'^atualizar-dados/$',views.update_user,name='update_user'),
    url(r'^alterar-senha/$',views.password_change,name='password_change'),
    url(r'^usuarios/$',views.userlist,name='userlist'),
    url(r'^$',views.index,name='index'),
]

catalog/urls.py
# coding=utf-8
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^materiais/$', views.product_list, name='product_list'),
    url(r'^(?P<slug>[\w_-]+)/$', views.category, name='category'),
    url(r'^material/(?P<slug>[\w_-]+)/$', views.product, name='product'),
]

checkout/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^pedido/adicionar/(?P<slug>[\w_-]+)/$', views.add_cart, name='add_cart'),
   	url(r'^relacao/$', views.cart_item, name='cart_item'),
   	url(r'^finalizar/$', views.checkout, name='checkout'),
   	url(r'^meus-pedidos/$', views.order_list, name='order_list'),
   	url(r'^meus-pedidos/(?P<pk>\d+)/$', views.order_detail, name='order_detail'),
   	url(r'^imprimir/(?P<pk>\d+)/$', views.printpdf, name='printpdf'),
]

sisalmox/urls.py
# coding=utf-8

from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout

from core import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^contato/$', views.contact, name='contact'),
    url(r'^legislacao/$', views.laws, name='laws'),
    url(r'^entrar/$', login,{'template_name': 'login.html'}, name='login'),
    url(r'^sair/$', logout,{'next_page': 'index'}, name='logout'),
    url(r'^conta/', include('accounts.urls', namespace='accounts')),
    url(r'^pedidos/', include('checkout.urls', namespace='checkout')),
    url(r'^requisicao/', include('catalog.urls', namespace='catalog')),
    url(r'^pesquisar/', include('searchengine.urls', namespace='searchengine')),
]

core/models.py
from django.db import models

# Create your models here.

core/forms.py
# coding=utf-8

from django import forms
from django.core.mail import send_mail
from django.conf import settings

class ContactForm(forms.Form):
    name = forms.CharField(label='Nome')
    email = forms.EmailField(label='E-mail')
    message = forms.CharField(label='Mensagem', widget=forms.Textarea())

    def send_mail(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        message = self.cleaned_data['message']
        message = 'Nome: {0}\nEmail: {1}\nMensagem: {2}'.format(name, email, message)
        send_mail(
        'Contato do Sistema de Pedidos', message, settings.DEFAULT_FROM_EMAIL,
        [settings.DEFAULT_FROM_EMAIL]
        )

core/views.py
# coding=utf-8
from django.shortcuts import get_object_or_404,render
from django.http import HttpResponse
from django.views.generic import View, TemplateView, CreateView
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin

User = get_user_model()

class IndexView(LoginRequiredMixin, TemplateView):
    template_name = 'index.html'

index = IndexView.as_view()

class ContactView(LoginRequiredMixin, TemplateView):
    template_name = 'contact.html'

contact = ContactView.as_view()

class LawsView(LoginRequiredMixin, TemplateView):
    template_name = 'laws.html'

laws = LawsView.as_view()

core/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Sistema de Almoxarifado - CES/UFCG</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>
  <body>
    <nav class="navbar navbar-inverse">
      <div class="container">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'index' %}">SisAlmox</a>
          </div>
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'index' %}">Início</a></li>
            <li><a href="{% url 'catalog:index' %}">Requisição de Material</a></li>
            <li><a href="{% url 'contact' %}">Contato</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-user"></span> Minha Conta <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'checkout:order_list' %}">Meus Pedidos</a></li>
                <li><a href="{% url 'accounts:password_change' %}">Alterar Senha</a></li>
                <li><a href="{% url 'accounts:update_user' %}">Atualizar Dados</a></li>
              </ul>
            </li>
            <li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-out"></span> Sair</a></li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      {% block container %}{% endblock %}
    </div>

    <div class="navbar navbar-default navbar-fixed-bottom">
      <p class="navbar-text pull-left"><a href="{% url 'index' %}">Início</a></p>
      <p class="navbar-text pull-left"><a href="{% url 'contact' %}">Contato</a></p>
      <p class="navbar-text pull-left"><a href="{% url 'laws' %}">Legislação</a></p>
      <p class="navbar-text pull-right"><a href="#top">Voltar ao Topo</a></p>
    </div>

  </body>
</html>

core/templates/contact.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}
  Contato | {{ block.super }}
{% endblock %}

{% block container %}
<div class="page-header">
  <h1>Contato</h1>
  <h2>Almoxarifado CES/UFCG</h2>
  <p>
    <h3>Funcionários</h3>
    <h4>Jeancarlo Meira de Melo</h4>
    <h4>Thiago Augusto dos Santos Ferreira</h4>
    <h4>José Eudes de Macêdo Dantas</h4>
  </p>
  <p>
    <h3>Telefone</h3>
    <h4>(83) 3372 1912</h4>
  </p>
  <p>
    <h3>E-mail</h3>
    <h4>amoxarifado.ces@ufcg.edu.br</h4>
  </p>
  <p>
    <h3>Endereço</h3>
    <h4>Acesso Maria Anita Furtado Coelho, sn</h4>
    <h4>Olho D'água da Bica, Cuité-PB</h4>
    <h4>CEP: 58.175-000</h4>
  </p>
  <p>
    <h3>Expediente</h3>
    <h4>de segunda a sexta das 7h00 às 12h00 e das 13h30 às 17h00</h4>
  </p>
</div>
{% endblock %}

core/templates/index.html
{% extends "base.html" %}

{% block container %}
<div class="jumbotron page-header">
	<h1>Sistema de Gestão de Almoxarifado</h1>
	<h2>Almoxarifado - CES/UFCG</h2>
	<p>Setor responsável pela recepção, armazenamento, controle e distribuição de materiais estocáveis,
		controle dos níveis de estoque, atendimento às requisições de materiais de toda a Universidade,
		acompanhamento de prazos de entrega de materiais junto aos fornecedores.</p>
</div>
{% endblock %}

core/templates/laws.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}
  Legislação | {{ block.super }}
{% endblock %}

{% block container %}
<div class="page-header">
  <h1>Legislação</h1>
  <h2>Almoxarifado CES/UFCG</h2>
  <p>
    <h3>Atribuições gerais<h3>
      <h4 align='justify'>Receber, armazenar e distribuir os materiais adquiridos pelo CES/UFCG; Receber a nota de empenho e encaminhar a mesma para o fornecedor; Respeitar os prazos legais de recebimento de material; Notificar o fornecedor se a entrega do material não ocorrer no prazo previsto; Conferir o material recebido, observando se o mesmo está compatível com o que foi empenhado; Emitir a NEM - Nota de Entrada de Material; Atestar a Nota Fiscal do fornecedor; Encaminhar o material recebido para o setor demandante; Emitir relatório mensal referente ao estoque e a toda a movimentação de material de consumo; Realizar o inventário anual.<h4>
  </p>
  <p>
    <h3>Regulamentação<h3>
      <h4><a href="https://pra.ufcg.edu.br/phocadownload/documentos/CCF/Cronograma%20de%20atividades%202018%20-%20Almoxarifado.pdf">Cronograma de Atividades 2018</a></h4>
  </p>
  <p>
      <h4><a href="http://www.comprasnet.gov.br/legislacao/in/in205_88.htm">Instrução Normativa N° 205, de 08 de abril de 1988</a></h4>
  </p>
</div>
{% endblock %}

core/templates/login.html
{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Sistema de Almoxarifado - CES/UFCG</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand"><b>Sistema de Almoxarifado CES/UFCG<b></a>
        </div>
      </div>
    </nav>


    <div class="container">
      <div class="row">
          <div class="col-md-8 col-md-offset-2">
              <div class="page-header">
                  <h1>Login</h1>
              </div>
              <form class="form-horizontal" method="post">
                  {% csrf_token %}
                  {% for error in form.non_field_errors %}
                  <div class="alert alert-danger">
                      {{ error }}
                  </div>
                  {% endfor %}
                  <fieldset>
                      <div class="form-group{% if form.username.errors %} has-error{% endif %}">
                        <label for="{{ form.username.auto_id }}" class="col-md-3 control-label">{{ form.username.label }}</label>
                        <div class="col-md-9">
                          {% render_field form.username class="form-control" %}
                          {% for error in form.username.errors %}
                          <span class="help-block">{{ error }}</span>
                          {% endfor %}
                        </div>
                      </div>
                      <div class="form-group{% if form.password.errors %} has-error{% endif %}">
                        <label for="{{ form.password.auto_id }}" class="col-md-3 control-label">{{ form.password.label }}</label>
                        <div class="col-md-9">
                          {% render_field form.password class="form-control" %}
                          {% for error in form.password.errors %}
                          <span class="help-block">{{ error }}</span>
                          {% endfor %}
                        </div>
                      </div>
                      <div class="form-group">
                        <div class="col-md-9 col-md-offset-3">
                          <p><button type="submit" class="btn btn-primary">Entrar</button></P>
                          <p><a href="#"data-toggle="popover" data-content="Favor entrar em contato: almoxarifado.ces@ufcg.edu.br Telefone: (83) 3372 1912">Esqueceu a senha?</a></p>
                          <p><a href="{% url 'accounts:register' %}">Criar Perfil</a></p>
                        </div>
                      </div>
                  </fieldset>
              </form>
          </div>
      </div>
    </div>

    <script>
    $(document).ready(function(){
        $('[data-toggle="popover"]').popover();
    });
    </script>

  </body>
</html>

core/templates/pagination.html
<div class="row">
  <div class="col-md-12">
    <nav>
      <ul class="pagination">
        {% for page in paginator.page_range %}
        <li{% if page_obj.number == page %} class="active" {% endif %}><a href="?page={{ page }}{{ getvars }}">{{ page }}</a></li>
        {% endfor %}
      </ul>
    </nav>
  </div>
</div>

core/templates/requisicao.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}
  Requisição de Material | {{ block.super }}
{% endblock %}

{% block container %}
<div class="page-header">
  <h1>Requisição</h1>
  <div class="list-group">
    <a href="#" class="list-group-item">First item</a>
    <a href="#" class="list-group-item">Second item</a>
    <a href="#" class="list-group-item">Third item</a>
  </div>
{% endblock %}