catalog/urls.py
# coding=utf-8
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^materiais/$', views.product_list, name='product_list'),
    url(r'^(?P<slug>[\w_-]+)/$', views.category, name='category'),
    url(r'^material/(?P<slug>[\w_-]+)/$', views.product, name='product'),
]

checkout/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^pedido/adicionar/(?P<slug>[\w_-]+)/$', views.add_cart, name='add_cart'),
   	url(r'^relacao/$', views.cart_item, name='cart_item'),
   	url(r'^finalizar/$', views.checkout, name='checkout'),
   	url(r'^meus-pedidos/$', views.order_list, name='order_list'),
   	url(r'^meus-pedidos/(?P<pk>\d+)/$', views.order_detail, name='order_detail'),
   	url(r'^imprimir/(?P<pk>\d+)/$', views.printpdf, name='printpdf'),
]

searchengine/urls.py
# coding=utf-8
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.search, name='search'),
    url(r'^resultados/$', views.results, name='results'),



]

sisalmox/urls.py
# coding=utf-8

from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout

from core import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^contato/$', views.contact, name='contact'),
    url(r'^legislacao/$', views.laws, name='laws'),
    url(r'^entrar/$', login,{'template_name': 'login.html'}, name='login'),
    url(r'^sair/$', logout,{'next_page': 'index'}, name='logout'),
    url(r'^conta/', include('accounts.urls', namespace='accounts')),
    url(r'^pedidos/', include('checkout.urls', namespace='checkout')),
    url(r'^requisicao/', include('catalog.urls', namespace='catalog')),
    url(r'^pesquisar/', include('searchengine.urls', namespace='searchengine')),
]

catalog/models.py
# coding=utf-8

from django.db import models
from django.core.urlresolvers import reverse
from django.forms.models import ModelForm
from django.forms.widgets import CheckboxSelectMultiple

class Category(models.Model):
    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Identificador', max_length=100, unique=True, help_text="Preenchido automaticamente, não editar.",)

    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog:category', kwargs={'slug':self.slug})


class Unidades(models.Model):
    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Identificador', max_length=100, unique=True, help_text="Preenchido automaticamente, não editar.",)

    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    class Meta:
        verbose_name = 'Unidade'
        verbose_name_plural = 'Unidades'
        ordering = ['name']

    def __str__(self):
        return self.name

class Product(models.Model):
    codigo = models.CharField('Código Comprasnet', max_length=6)
    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Identificador', max_length=100, unique=True, help_text="Preenchido automaticamente, não editar.",)
    category = models.ForeignKey('catalog.Category', verbose_name='Categoria')
    description = models.TextField('Descrição')
    unid = models.ForeignKey('catalog.Unidades', verbose_name='Unidades')
    price = models.DecimalField('Preço', decimal_places=2, max_digits=8)
    pregao = models.CharField('Pregão da última aquisição', max_length=8, help_text="Preencher no formato nnn/aaaa",)

    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    class Meta:
        verbose_name = 'Produto'
        verbose_name_plural = 'Produtos'
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog:product', kwargs={'slug':self.slug})

catalog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, TemplateView
from .models import Product, Category
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required


class ProductListView(LoginRequiredMixin,ListView):
    model = Product
    template_name = 'catalog/product_list.html'
    context_object_name = 'product_list'
    paginate_by = 10

product_list = ProductListView.as_view()

class CategoryListView(LoginRequiredMixin,ListView):
    template_name = 'catalog/category.html'
    context_object_name = 'product_list'
    paginate_by = 10

    def get_queryset(self):
        return Product.objects.filter(category__slug=self.kwargs['slug'])

    def get_context_data(self,**kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        context['current_category'] = get_object_or_404(Category, slug=self.kwargs['slug'])
        return context

category = CategoryListView.as_view()

def product(request, slug):
    product = Product.objects.get(slug=slug)
    context = {
        'product': product,
    }
    return render(request, 'catalog/product.html', context)

class IndexView(LoginRequiredMixin, TemplateView):
    template_name = 'catalog/index.html'

index = IndexView.as_view()

catalog/templates/catalog/category.html
{% extends "catalog/index.html" %}

{% load pagination %}

{% block title %}
  {{ current_category }} | {{ block.super }}
{% endblock %}

{% block catalog_container %}
<div class="page-header">
  <h1>{{ current_category }}</h1>
</div>

<table class="table table-bordered">
  <thead>
    <tr>
      <th width="70">Código</th>
      <th width="200">Descrição</th>
      <th width="100">Unidade</th>
      <th class="text-center" colspan="2">Ações</th>
    </tr>
  </thead>
  <tbody>
    {% for product in product_list %}
    <tr>
      <td>{{ product.codigo }}</td>
      <td>{{ product }}</td>
      <td>{{ product.unid }}</td>
      <td class="text-center"  width="80">
        <a href="{{ product.get_absolute_url }}" class="btn btn-success" role="button">Detalhes</a>
      </td>
      <td class="text-center"  width="100">
        <a href="{% url 'checkout:add_cart' product.slug %}" class="btn btn-primary" role="button">Adicionar ao Pedido</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% pagination request paginator page_obj %}
{% endblock %}

catalog/templates/catalog/index.html
{% extends "base.html" %}

{% block title %}Requisição de Material{% endblock %}

{% block container %}
<div class="col-md-3">
  <div class="row"><p></div>
  <div class="row"><p></div>
  <div class="row"><p></div>
  <div class="row"><p></div>
    
  <div class="list-group">
    <a href="{% url 'checkout:cart_item' %}"><button class="list-group-item">Requisição Atual</button></a>
    <a href="{% url 'catalog:product_list' %}"><button class="list-group-item">Consultar Estoque</button></a>
    <a href="{% url 'searchengine:search' %}"><button class="list-group-item">Pesquisar</button></a>
    <a class="list-group-item" class="dropdown-toggle" data-toggle="dropdown">Categorias <span class="caret"></span></a>
      <ul class="dropdown-menu" role="menu">
        {% for category in categories %}
        <li><a href="{{ category.get_absolute_url }}">{{ category }}</a></li>
        {% endfor %}
      </ul>
  </div>
</div>
    <div class="col-md-9">
      {% block catalog_container %}{% endblock %}
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product.html
{% extends "catalog/index.html" %}

{% block title %}
  {{ product }} | {{ block.super }}
{% endblock %}

{% block catalog_container %}
<div class="page-header">
  <h1>{{ product }}</h1>
</div>
<div class="row">
  <div class="col-sm-9">
    <label>Código: </label>
      {{ product.codigo }}
    </p>
    <label>Descrição: </label>
      {{ product.description }}
    </p>
    <label>Unidade: </label>
      {{ product.unid }}
    </p>
    <p class="text-right">
      <a href="{% url 'checkout:add_cart' product.slug %}" class="btn btn-primary">Adicionar ao Pedido</a>
    </p>
  </div>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends "catalog/index.html" %}

{% load widget_tweaks %}

{% load pagination %}

{% block title %}
  Listagem de Produtos | {{ block.super }}
{% endblock %}

{% block catalog_container %}
<div class="page-header">
  <h1>Produtos</h1>
</div>

<table class="table table-bordered">
  <thead>
    <tr>
      <th width="70">Código</th>
      <th width="200">Descrição</th>
      <th width="100">Unidade</th>
      <th class="text-center" colspan="2">Ações</th>
    </tr>
  </thead>
  <tbody>
    {% for product in product_list %}
    <tr>
      <td>{{ product.codigo }}</td>
      <td>{{ product }}</td>
      <td>{{ product.unid }}</td>
      <td class="text-center"  width="80">
      <a href="{{ product.get_absolute_url }}" class="btn btn-success" role="button">Detalhes</a>
      </td>
      <td class="text-center"  width="100">
        <a href="{% url 'checkout:add_cart' product.slug %}" class="btn btn-primary" role="button">Adicionar ao Pedido</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% pagination request paginator page_obj %}
{% endblock %}